# Generated by Django 5.0.3 on 2024-03-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_image_comment_reply_to_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="reply_to_image",
        ),
        migrations.AddField(
            model_name="comment",
            name="image_url",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
